### ISSUE TITLE
After migrating from travajdk to jbr17 redefineClasses fails with ObjectCollectedException

### ISSUE THREAD

**Issue by kochetkovSergeY** [JetBrains/JetBrainsRuntime#264] opened 2024-01-11 10:02 UTC
I'm trying to reload classes multiple times, every time I'm attaching and disposing jvm again, it works fine for a some time but some time later it throws ObjectCollectedException:

pseudo code for every reload step:

```
jvm.attach(...);
List<ReferenceType> classTypes = vm.classesByName(className);
classTypes.forEach(classType->{
    try {
      Map<ReferenceType, byte[]> map = new HasMap<>();
      map.put(classType, getNewClassBytes(className));
      jvm.redefineClasses(map);
    }
    catch (Exception ex) {
      logger.error(ex.getMessage(), ex);
    }
});

jvm.dispose();
```

Could VirtualMachine.classesByName return collected ClassType-s?

error stack:
```
Caused by: com.sun.jdi.ObjectCollectedException
	at jdk.jdi/com.sun.tools.jdi.JDWPException.toJDIException(JDWPException.java:55)
	at jdk.jdi/com.sun.tools.jdi.VirtualMachineImpl.redefineClasses(VirtualMachineImpl.java:433)
```

Error not cccuring if I remove jvm.attach and jvm.dispose calls, but i want to free up port for debug purposes for example

enviroment:
latest jbr 17
latest hotswap-agent.jar built from master branch

**Comment by kochetkovSergeY** [comment] 2024-01-11 10:10
Or it's an openjdk issue?

**Comment by skybber** [comment] 2024-01-11 10:44
Are you using `-XX:+AllowEnhancedClassRedefinition` (it is not deafult in jbr17 as is in TravaJDK) ?

**Comment by kochetkovSergeY** [comment] 2024-01-11 11:08
@skybber yes, 
we have two settings
-XX:+AllowEnhancedClassRedefinition
-XX:HotswapAgent=fatjar

**Comment by skybber** [comment] 2024-01-11 13:03
Could you please create a minimal example reproducing this bug?

**Comment by kochetkovSergeY** [comment] 2024-01-12 09:04
it will take some time (not fast), but in debug i saw that VirtualMachine.classesByName returned collected Classtype (there is an error in toString() call)

**Comment by kochetkovSergeY** [comment] 2024-01-12 09:12
I think the problem is in dispose method, the doc says:

`Garbage collection is re-enabled in all cases where it was disabled through ObjectReference.disableCollection.`

But with `-XX:+AllowEnhancedClassRedefinition`  it shouldn't collect ClassType?

**Comment by skybber** [comment] 2024-01-13 15:32
If -XX:+AllowEnhancedClassRedefinition is used, the redefinition of class C to C' generates a new instance (of java.lang.Class) for class C' and updates all references to C to now point to C'. Therefore, in your specific scenario, there is likely a ReferenceType for the old class C and another ReferenceType for the new class C'. If `-XX:-ClassUnloading` is not used, the subsequent full GC will reclaim the old instance of C'. If you attempt to access the old ReferenceType, an ObjectCollectedException will be thrown. Ideally, DCEVM should keep older instances (instances of type Class) of C' alive, but currently, they are collected since there are no references in the heap pointing to them.

Otherwise you can confirm this by using `-XX:-ClassUnloading`.

**Comment by kochetkovSergeY** [comment] 2024-01-17 12:44
Jvm crashes with this paramter `-XX:-ClassUnloading` on the first attempt to redefine class...
[hs_err_pid21268.log](https://github.com/JetBrains/JetBrainsRuntime/files/13963315/hs_err_pid21268.log)

**Comment by skybber** [comment] 2024-01-17 14:06
It's hard to resolve the problem from supplied hs_err file, since stack mapping is missing. Could you please create an example reproducing this bug?

**Comment by skybber** [comment] 2024-01-17 17:52
> Jvm crashes with this paramter `-XX:-ClassUnloading` on the first attempt to redefine class... [hs_err_pid21268.log](https://github.com/JetBrains/JetBrainsRuntime/files/13963315/hs_err_pid21268.log)

I'm able to reproduce the crash now. It seems, that it is related to G1 GC. You can try `-XX:+UseSerialGC` as a workaround for now.

**Comment by kochetkovSergeY** [comment] 2024-01-18 10:34
> > Jvm crashes with this paramter `-XX:-ClassUnloading` on the first attempt to redefine class... [hs_err_pid21268.log](https://github.com/JetBrains/JetBrainsRuntime/files/13963315/hs_err_pid21268.log)
> 
> I'm able to reproduce the crash now. It seems, that it is related to G1 GC. You can try `-XX:+UseSerialGC` as a workaround for now.

I tied this, jvm not crashing now but `-XX:-ClassUnloading` not helped at all, error still occuring

**Comment by skybber** [comment] 2024-01-18 20:09
Great job, thanks! It crashes on version 17.0.9 for me, but NO on the not yet released, new version with new dcevm fixes. It survives even 1k redefinitions. Fixes should be released in the next JBR releases.

**Comment by skybber** [comment] 2024-01-22 09:25
There is a jbr branch with the patch available at:

https://github.com/JetBrains/JetBrainsRuntime/tree/vladimir.dvorak/JBR-6363

if you know how to build a JDK, it would be great if you could try it on your case, but don't feel it's necessary

**Comment by skybber** [comment] 2024-01-28 18:36
I have reproduced this error even with the latest version of JBR. It seems that the error occurs when repeatedly connecting and disconnecting HotSwapper. Normally the debugger doesn't connect 100 times, so it hasn't appeared yet.  Could you use Hotswapper as singleton with one connection as workaround?

**Comment by kochetkovSergeY** [comment] 2024-01-31 10:12
We've already used this workaround, but we have cases when we need to connect to app debug port by other different apps,  and there we have been catched this problem...

**Comment by cvictory** [comment] 2024-02-08 02:39
@skybber @kochetkovSergeY  the spring issue is https://github.com/HotswapProjects/HotswapAgent/issues/530 ?

**Comment by skybber** [comment] 2024-02-08 07:38
@cvictory Yes please.

**Comment by kochetkovSergeY** [comment] 2024-03-27 12:20
@skybber I've seen that the bug was fixed in https://youtrack.jetbrains.com/issue/JBR-6648  but in newest jbr builds problem from   https://youtrack.jetbrains.com/issue/JBR-6648 is actual, forgot to merge?

**Comment by vprovodin** [comment] 2024-03-27 12:26
BTW it was merged into https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.10b1207.6

**Comment by sofit** [comment] 2024-03-27 12:42
> BTW it was merged into https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.10b1207.6

there are no changes in latest release [Release 17.0.10-b829.27](https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.10b829.27)

**Comment by sofit** [comment] 2024-03-27 12:43
> BTW it was merged into https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.10b1207.6

there are no changes in latest release https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.10b829.27

**Comment by kochetkovSergeY** [comment] 2024-03-28 12:16
https://github.com/JetBrains/JetBrainsRuntime/releases

**Comment by kochetkovSergeY** [comment] 2024-03-29 05:41
oh now I understand, thank you, build number like hotfix version, this was the reason:

![image](https://github.com/JetBrains/JetBrainsRuntime/assets/5997966/27ed92a6-408d-4677-8654-aae0f15437df)

**Closed** 2024-04-01 06:33 UTC
