### ISSUE TITLE
The input of Linux Fcitx displays abnormally

### ISSUE THREAD

**Issue by Deathef** [JetBrains/JetBrainsRuntime#67] opened 2021-06-30 02:27 UTC
OS: Ubuntu 20.04
IDEA: 2021.1.3
Runtime Version: 11.0.11+9-b1341.60 amd64

This problem existed in the 2020.1 version, and it was not fixed until the 2021.1.3 version. This is a serious bug that affects usage. Some developers in the community have provided patches to fix this problem. When can the official incorporate this patch?

**Comment by vprovodin** [comment] 2021-06-30 03:44
Thank you for submitting the issue. We regret the inconvenience caused to you.

Could you please provide us with the detailed description of the problem & steps reproducing this issue?

> Some developers in the community have provided patches to fix this problem.
Unfortunately we have got neither pull requests related to this issue nor patches in any other format. Any references to these fix would be appreciated?

**Comment by Deathef** [comment] 2021-06-30 05:34
> Thank you for submitting the issue. We regret the inconvenience caused to you.
> 
> Could you please provide us with the detailed description of the problem & steps reproducing this issue?
> 
> > Some developers in the community have provided patches to fix this problem.
> 
> Unfortunately we have got neither pull requests related to this issue nor patches in any other format. Any references to these fix would be appreciated?

Use any fcitx input. When inputting Chinese or Japanese in IDEA, the input software cannot get the focus position of the cursor.
This patch is not provided by me, sorry I can’t submit a pull requests. But I can provide a git repository of patches. https://github.com/prehonor/myJetBrainsRuntime

**Comment by Deathef** [comment] 2021-06-30 05:39
I saw a lot of people in the issue and I encountered the same problem.

**Comment by Gold-Z** [comment] 2021-07-08 03:42
I encountered the same problem.

**Comment by ExplodingDragon** [comment] 2021-08-05 07:49
I encountered the same problem.

**Comment by dejin0916** [comment] 2021-08-14 03:19
I encountered the same problem.

**Comment by zgrwbb** [comment] 2021-12-08 13:16
俺也一样

**Comment by dejin0916** [comment] 2021-12-11 12:55
This bug exits with 8 years and with another 6 month passed,it hasn't been fixed yet.This is the discussion about this bug 
https://youtrack.jetbrains.com/issue/JBR-2460

**Comment by SergeFan** [comment] 2021-12-15 13:15
Yeah, more than 8 years. Please fix this bug, it only needs a patch. So, PLZ.

**Comment by cnmade** [comment] 2021-12-17 00:43
别抱怨了，实际上人民应该付出行动来修正。有没有人提交过pull request。

**Comment by jimersylee** [comment] 2022-06-27 07:55
same problem,please fix it

**Comment by Deathef** [comment] 2022-06-28 03:14
> Unfortunately, this is an upstream OpenJDK bug. Even my own Java window program has this problem. The patch mentioned above can solve both JetBrains softwares and my own one. I guess not only should we ask JetBrians to add that patch but also we should complain that to upstream OpenJDK and Oracle, since if they do not fix it at the upstream, this bug will always be there for Java 17, 21, 28, and so on...

I was going to submit feedback to OpenJDK, but I saw this feedback in OpenJDK's Issue, [JDK-8279052](https://bugs.openjdk.org/browse/JDK-8279052).

**Comment by aohanhongzhi** [comment] 2023-04-01 03:43
now the problem is nobody PR. 
I hope somebody do this

**Comment by vprovodin** [comment] 2023-04-02 02:15
@NikitkoCent Could you please take a look at suggested patches fixing this issue

> This patch is not provided by me, sorry I can’t submit a pull requests. But I can provide a git repository of patches. https://github.com/prehonor/myJetBrainsRuntime

**Comment by avu** [comment] 2023-04-03 10:34
Could you please report using our bug database https://youtrack.jetbrains.com/issues/JBR

**Comment by Bryan2333** [comment] 2023-04-09 15:59
> Could you please report using our bug database https://youtrack.jetbrains.com/issues/JBR

Actually, this bug is reported almost 10 years ago. See https://youtrack.jetbrains.com/issue/JBR-2460. And the bug is still not fixed.

**Comment by hellolxc** [comment] 2023-05-05 13:33
I have the same problem

**Comment by M4n5ter** [comment] 2023-05-06 02:34
i have the same problem

**Comment by ihipop** [comment] 2023-05-08 06:12
> Could you please report using our bug database https://youtrack.jetbrains.com/issues/JBR

Could you [please merge this patch](https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64) so we can [close this issue](https://youtrack.jetbrains.com/issue/JBR-2460)

**Comment by Yu-Xiao-Sheng** [comment] 2024-01-12 06:48
I encountered the same problem. I searched for various solutions on the Internet and found a patch in the community: [https://github.com/prehonor/myJetBrainsRuntime](https://github.com/prehonor/myJetBrainsRuntime)
However, because the patch is too old and cannot be used directly in the current version of the code, I compared the patch modifications and manually modified the same content in the latest version submission (50933cd23e3c65a4c4ab2f10cc3f230706ab1719), and ensured successful compilation. For this purpose, I forked a warehouse for reference only: https://github.com/Yu-Xiao-Sheng/JetBrainsRuntime/tree/jbr17

At the same time, I generated a new patch file based on the changed content. The file `FixedLinuxFcitx.patch` is located in the `jbr17` branch of the warehouse. I hope it can be helpful to you.

If the `JetBrains/JetBrainsRuntime` warehouse continues to be updated in the future, I think a convenient way is to merge the contents of the two warehouses `JetBrains/JetBrainsRuntime` and `Yu-Xiao-Sheng/JetBrainsRuntime` and recompile, but the validity of subsequent changes cannot be guaranteed.

Sorry I can't submit a pull request, I don't know much about it yet.

**Comment by ihipop** [comment] 2024-01-12 06:56
> I encountered the same problem. I searched for various solutions on the Internet and found a patch in the community: https://github.com/prehonor/myJetBrainsRuntime However, because the patch is too old and cannot be used directly in the current version of the code, I compared the patch modifications and manually modified the same content in the latest version submission ([50933cd](https://github.com/JetBrains/JetBrainsRuntime/commit/50933cd23e3c65a4c4ab2f10cc3f230706ab1719)), and ensured successful compilation. For this purpose, I forked a warehouse for reference only: https://github.com/Yu-Xiao-Sheng/JetBrainsRuntime/tree/jbr17
> 
> At the same time, I generated a new patch file based on the changed content. The file `FixedLinuxFcitx.patch` is located in the `jbr17` branch of the warehouse. I hope it can be helpful to you.
> 
> If the `JetBrains/JetBrainsRuntime` warehouse continues to be updated in the future, I think a convenient way is to merge the contents of the two warehouses `JetBrains/JetBrainsRuntime` and `Yu-Xiao-Sheng/JetBrainsRuntime` and recompile, but the validity of subsequent changes cannot be guaranteed.
> 
> Sorry I can't submit a pull request, I don't know much about it yet.

They have already had an official try on this issue https://youtrack.jetbrains.com/issue/JBR-2460/Wrong-position-of-input-window-and-no-input-preview-with-fcitx-and-ubuntu-13.04

it's Fixed in JBR builds: jbr17.1162.7

**Comment by aohanhongzhi** [comment] 2024-01-12 06:56
> I encountered the same problem. I searched(搜索) for various solutions on the Internet and found(发现) a patch(补丁) in the community(社区): https://github.com/prehonor/myJetBrainsRuntime我遇到了同样的问题。我在互联网上搜索了各种解决方案，并在社区中找到了一个补丁：https://github.com/prehonor/myJetBrainsRuntime However, because the patch(补丁) is too old and cannot be used(使用) directly(直接) in the current(当前) version(版本) of the code(代码), I compared the patch(补丁) modifications and manually modified the same content(内容) in the latest version(版本) submission ([50933cd](https://github.com/JetBrains/JetBrainsRuntime/commit/50933cd23e3c65a4c4ab2f10cc3f230706ab1719)), and ensured successful(成功) compilation. For this purpose(宗旨), I forked a warehouse(仓库) for reference(参考) only: https://github.com/Yu-Xiao-Sheng/JetBrainsRuntime/tree/jbr17但是，由于补丁太旧，无法在当前版本的代码中直接使用，所以我在最新版本提交（ 50933cd ）中对比了补丁修改并手动修改了相同的内容，并确保编译成功。为此，我分叉了一个仓库仅供参考：https://github.com/Yu-Xiao-Sheng/JetBrainsRuntime/tree/jbr17
> 
> At the same time, I generated a new patch(补丁) file based on the changed content(内容). The file `FixedLinuxFcitx.patch` is located in the `jbr17` branch(分公司) of the warehouse(仓库). I hope it can be helpful(乐于助人) to you.同时，我根据更改的内容生成了一个新的补丁文件。该文件 `FixedLinuxFcitx.patch` 位于仓库的 `jbr17` 分支中。希望对您有所帮助。
> 
> If the `JetBrains/JetBrainsRuntime` warehouse(仓库) continues to be updated in the future(未来), I think a convenient(方便) way is to merge(合并) the contents(内容) of the two warehouses(仓库) `JetBrains/JetBrainsRuntime` and `Yu-Xiao-Sheng/JetBrainsRuntime` and recompile, but the validity(有效性) of subsequent(后续) changes cannot be guaranteed.如果以后仓库继续更新，我觉得方便的办法是合并两个 `JetBrains/JetBrainsRuntime` 仓库的内容 `JetBrains/JetBrainsRuntime` ， `Yu-Xiao-Sheng/JetBrainsRuntime` 然后重新编译，但后续更改的有效性无法保证。
> 
> Sorry I can't submit(提交) a pull request(请求), I don't know much about it yet.对不起，我无法提交拉取请求，我还不太了解。

This problem has been fixed in the official repository

**Comment by Yu-Xiao-Sheng** [comment] 2024-01-12 07:08
> > I encountered the same problem. I searched for various solutions on the Internet and found a patch in the community: https://github.com/prehonor/myJetBrainsRuntime However, because the patch is too old and cannot be used directly in the current version of the code, I compared the patch modifications and manually modified the same content in the latest version submission ([50933cd](https://github.com/JetBrains/JetBrainsRuntime/commit/50933cd23e3c65a4c4ab2f10cc3f230706ab1719)), and ensured successful compilation. For this purpose, I forked a warehouse for reference only: https://github.com/Yu-Xiao-Sheng/JetBrainsRuntime/tree/jbr17我遇到了同样的问题。我在网上搜索了各种解决方案，在社区里找到了一个补丁： https://github.com/prehonor/myJetBrainsRuntime 但是，由于补丁太旧，无法在当前版本的代码中直接使用，所以我对比了补丁修改，并在最新版本提交（50933cd）中手动修改了相同的内容，并确保编译成功。为此，我分叉了一个仓库仅供参考：https://github.com/Yu-Xiao-Sheng/JetBrainsRuntime/tree/jbr17
> > At the same time, I generated a new patch file based on the changed content. The file `FixedLinuxFcitx.patch` is located in the `jbr17` branch of the warehouse. I hope it can be helpful to you.同时，我根据更改的内容生成了一个新的补丁文件。该文件 `FixedLinuxFcitx.patch` 位于仓库的 `jbr17` 分支中。希望对您有所帮助。
> > If the `JetBrains/JetBrainsRuntime` warehouse continues to be updated in the future, I think a convenient way is to merge the contents of the two warehouses `JetBrains/JetBrainsRuntime` and `Yu-Xiao-Sheng/JetBrainsRuntime` and recompile, but the validity of subsequent changes cannot be guaranteed.如果以后仓库继续更新，我觉得方便的办法是合并两个 `JetBrains/JetBrainsRuntime` 仓库的内容 `JetBrains/JetBrainsRuntime` ， `Yu-Xiao-Sheng/JetBrainsRuntime` 然后重新编译，但后续更改的有效性无法保证。
> > Sorry I can't submit a pull request, I don't know much about it yet.对不起，我无法提交拉取请求，我还不太了解。
> 
> They have already had an official try on this issue https://youtrack.jetbrains.com/issue/JBR-2460/Wrong-position-of-input-window-and-no-input-preview-with-fcitx-and-ubuntu-13.04他们已经对这个问题进行了正式尝试 https://youtrack.jetbrains.com/issue/JBR-2460/Wrong-position-of-input-window-and-no-input-preview-with-fcitx-and-ubuntu-13.04
> 
> it's Fixed in JBR builds: jbr17.1162.7它在 JBR 版本中已修复：jbr17.1162.7

Great, it turned out to be recently fixed!

**Comment by ihipop** [comment] 2024-01-12 07:10
@Yu-Xiao-Sheng try 2023.3.2, it just works like a charm

**Comment by Yu-Xiao-Sheng** [comment] 2024-01-12 07:25
> @Yu-Xiao-Sheng try 2023.3.2, it just works like a charm试试 2023.3.2，它就像一个魅力

Yes, I am using Intellij IDEA2023.3.2 on Ubuntu22.04. Unfortunately, I also encountered this problem. Apart from this problem, it works really well.

![image](https://github.com/JetBrains/JetBrainsRuntime/assets/46524350/6608438f-e186-4569-a013-3a7a6513b7ef)

I'm not sure if it's normal for other people to be in this kind of environment

**Comment by ihipop** [comment] 2024-01-12 07:30
> > @Yu-Xiao-Sheng try 2023.3.2, it just works like a charm试试 2023.3.2，它就像一个魅力
> 
> Yes, I am using Intellij IDEA2023.3.2 on Ubuntu22.04. Unfortunately, I also encountered this problem. Apart from this problem, it works really well.
> 
> ![image](https://private-user-images.githubusercontent.com/46524350/296159846-6608438f-e186-4569-a013-3a7a6513b7ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDQ2OTMsIm5iZiI6MTcwNTA0NDM5MywicGF0aCI6Ii80NjUyNDM1MC8yOTYxNTk4NDYtNjYwODQzOGYtZTE4Ni00NTY5LWEwMTMtM2E3YTY1MTNiN2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA3MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMWY0MGNkZTE2MjcwZDc1Y2YyY2I0ZjNhOTNlZTEwZDFjYmY2NTM1MzE1OGNiOTkzYTEyNjJjOTY1MTQ3MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IaS1dUgKLD9PETBHp_MTO_OwwXNjruW67N6VJMDuxoU)
> 
> I'm not sure if it's normal for other people to be in this kind of environment

which input method are you using? ibus or fcitx5?

What's your JBR version of Intellij IDEA 2023.3.2 ? I've tried PHPStorm/Goland/Ride  2023.3.2, both works well with fcitx5

can you paste this command output?

```bash
env |grep -i IM_ 
```

**Comment by Yu-Xiao-Sheng** [comment] 2024-01-12 07:33
> > > @Yu-Xiao-Sheng try 2023.3.2, it just works like a charm试试 2023.3.2，它就像一个魅力try 2023.3.2， it just works like a charm试试 2023.3.2，它就像一个魅力
> > 
> > 
> > Yes, I am using Intellij IDEA2023.3.2 on Ubuntu22.04. Unfortunately, I also encountered this problem. Apart from this problem, it works really well.是的，我在 Ubuntu22.04 上使用 Intellij IDEA2023.3.2。不幸的是，我也遇到了这个问题。除了这个问题之外，它的工作非常好。
> > ![image](https://private-user-images.githubusercontent.com/46524350/296159846-6608438f-e186-4569-a013-3a7a6513b7ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDQ2OTMsIm5iZiI6MTcwNTA0NDM5MywicGF0aCI6Ii80NjUyNDM1MC8yOTYxNTk4NDYtNjYwODQzOGYtZTE4Ni00NTY5LWEwMTMtM2E3YTY1MTNiN2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA3MjYzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMWY0MGNkZTE2MjcwZDc1Y2YyY2I0ZjNhOTNlZTEwZDFjYmY2NTM1MzE1OGNiOTkzYTEyNjJjOTY1MTQ3MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IaS1dUgKLD9PETBHp_MTO_OwwXNjruW67N6VJMDuxoU)
> > I'm not sure if it's normal for other people to be in this kind of environment我不确定其他人处于这种环境中是否正常
> 
> which input method are you using? ibus or fcitx5?您使用的是哪种输入法？IBUS还是FCITX5？
> 
> What's your JBR version of Intellij IDEA 2023.3.2 ? I've tried PHPStorm/Goland/Ride 2023.3.2, both works well with fcitx5您的 Intellij IDEA 2023.3.2 的 JBR 版本是什么？我试过 PHPStorm/Goland/Ride 2023.3.2，两者都适用于 fcitx5
> 
> can you paste this command output?你能粘贴这个命令输出吗？
> 
> ```shell
> env |grep -i IM_ 
> ```
Of course, this is the result:
![image](https://github.com/JetBrains/JetBrainsRuntime/assets/46524350/fedd81dc-237d-495b-b7ea-c74ad3e8412a)


I am using fcitx4.2.9.8

**Comment by ihipop** [comment] 2024-01-12 07:45
I doubt that You're not using a Fixed version of JBR, the genuine version of 2023.3.2 is bundled with 
jbr17.1087.9 ,this version has a patch for this issue backported
![image](https://github.com/JetBrains/JetBrainsRuntime/assets/423077/cdd6ed7a-a1d9-4c0d-a32b-f25417a1d510)

if you can confirm  that the version of JBR is jbr17.1087.9, I think there is some problem with your fictx4, I can not test with fictx4 because I'm using fcitx5

**Comment by Yu-Xiao-Sheng** [comment] 2024-01-12 07:58
> I doubt that You're not using a Fixed version of JBR, the genuine version of 2023.3.2 is bundled with jbr17.1087.9 ,this version has a patch for this issue backported ![image](https://private-user-images.githubusercontent.com/423077/296164504-cdd6ed7a-a1d9-4c0d-a32b-f25417a1d510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDYwNjksIm5iZiI6MTcwNTA0NTc2OSwicGF0aCI6Ii80MjMwNzcvMjk2MTY0NTA0LWNkZDZlZDdhLWExZDktNGMwZC1hMzJiLWYyNTQxN2ExZDUxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNzQ5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmQwZDAyYWFlNWU5ODkwNjllZDk5NTMxZjg1OGY2NTI0MGI3NWE0NGFhMDdlMDk0ZmE0N2FiMDAyM2MyZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MumRECayfari4wNyPrKE3jqZT5nD7lnbHSK5ZKB3b4U) ![image](https://private-user-images.githubusercontent.com/423077/296164925-3c9ba37d-2366-40fc-9ccf-0882a9e059b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDYwNjksIm5iZiI6MTcwNTA0NTc2OSwicGF0aCI6Ii80MjMwNzcvMjk2MTY0OTI1LTNjOWJhMzdkLTIzNjYtNDBmYy05Y2NmLTA4ODJhOWUwNTliNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNzQ5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODk2YjIyNjFiOTQ3MzQ0ODFmY2E3YTI3MjA0NjAyY2FmNTA3ZjBmMWI1ZTlkNWQ4NzViODhlMmM5OWNmNTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J6EGmBMDdJe-a2ktXYeTdeGHZ0i0VALqA2XWUNr6F4g)
> 
> if you can confirm that the version of JBR is jbr17.1087.9, I think there is some problem with your fictx4, I can not test with fictx4 because I'm using fcitx5

I think you are right, before I replaced my own compiled jbr, the backup version of the bound jbr runtime environment was jbr17.1087.7
![image](https://github.com/JetBrains/JetBrainsRuntime/assets/46524350/aa0a7bfc-fd4c-42b6-86cd-28307d34985f)

**Comment by Yu-Xiao-Sheng** [comment] 2024-01-12 07:59
> > I doubt that You're not using a Fixed version of JBR, the genuine version of 2023.3.2 is bundled with jbr17.1087.9 ,this version has a patch for this issue backported 我怀疑您没有使用 JBR 的固定版本，2023.3.2 的正版与 jbr17.1087.9 捆绑在一起，此版本针对此问题向后移植了补丁![image](https://private-user-images.githubusercontent.com/423077/296164504-cdd6ed7a-a1d9-4c0d-a32b-f25417a1d510.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDYwNjksIm5iZiI6MTcwNTA0NTc2OSwicGF0aCI6Ii80MjMwNzcvMjk2MTY0NTA0LWNkZDZlZDdhLWExZDktNGMwZC1hMzJiLWYyNTQxN2ExZDUxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNzQ5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMmQwZDAyYWFlNWU5ODkwNjllZDk5NTMxZjg1OGY2NTI0MGI3NWE0NGFhMDdlMDk0ZmE0N2FiMDAyM2MyZWIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MumRECayfari4wNyPrKE3jqZT5nD7lnbHSK5ZKB3b4U) ![image](https://private-user-images.githubusercontent.com/423077/296164925-3c9ba37d-2366-40fc-9ccf-0882a9e059b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDYwNjksIm5iZiI6MTcwNTA0NTc2OSwicGF0aCI6Ii80MjMwNzcvMjk2MTY0OTI1LTNjOWJhMzdkLTIzNjYtNDBmYy05Y2NmLTA4ODJhOWUwNTliNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNzQ5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODk2YjIyNjFiOTQ3MzQ0ODFmY2E3YTI3MjA0NjAyY2FmNTA3ZjBmMWI1ZTlkNWQ4NzViODhlMmM5OWNmNTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.J6EGmBMDdJe-a2ktXYeTdeGHZ0i0VALqA2XWUNr6F4g)
> > if you can confirm that the version of JBR is jbr17.1087.9, I think there is some problem with your fictx4, I can not test with fictx4 because I'm using fcitx5如果你能确认JBR的版本是jbr17.1087.9，我认为你的fictx4有一些问题，我不能用fictx4测试，因为我使用的是fcitx5
> 
> I think you are right, before I replaced my own compiled jbr, the backup version of the bound jbr runtime environment was jbr17.1087.7我想你是对的，在我替换我自己编译的jbr之前，绑定的jbr运行时环境的备份版本是jbr17.1087.7 ![image](https://private-user-images.githubusercontent.com/46524350/296167598-aa0a7bfc-fd4c-42b6-86cd-28307d34985f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNDY2MTAsIm5iZiI6MTcwNTA0NjMxMCwicGF0aCI6Ii80NjUyNDM1MC8yOTYxNjc1OTgtYWEwYTdiZmMtZmQ0Yy00MmI2LTg2Y2QtMjgzMDdkMzQ5ODVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDA3NTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkY2ZiNGM3Y2JlYzIwMjhjOTU0ZThkMDNlN2M3YmE5ZDA1MTg4ZjYwN2FlZjZjZThhOGQ0OWY2Njg4ZDBhMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0-6ELmFgLFWDYeTAHEte4a-b8MMPooJJct278wSQp5M)

I think, maybe if I install Intellj a few days later, I won't have this problem.

**Comment by ihipop** [comment] 2024-01-12 08:03
you can just reset the bundle JBR version, It will work again

double press the shift key , then input "runtime" in the actions tab, and reset the JBR settings in the following dialog

**Comment by Yu-Xiao-Sheng** [comment] 2024-01-12 08:11
> you can just reset the bundle JBR version, It will work again您可以重置捆绑的 JBR 版本，它将再次工作
> 
> double press the shift key , then input "runtime" in the actions tab, and reset the JBR settings in the following dialog双击 Shift 键，然后在“操作”选项卡中输入“运行时”，并在以下对话框中重置 JBR 设置

This is great, I have successfully changed to the latest runtime version and the problem no longer exists in this jbe version!

![image](https://github.com/JetBrains/JetBrainsRuntime/assets/46524350/d0c59e18-6856-4fcc-9135-0701e50a4141)

**Comment by NikitkoCent** [comment] 2024-01-23 18:25
As you may have noticed, the issue (https://youtrack.jetbrains.com/issue/JBR-2460) was fixed in 2023.3.2, so I'm closing it. If you experience some problems with it, feel free to leave a comment through the provided link.

**Closed by NikitkoCent** 2024-01-23 18:25 UTC
