### ISSUE TITLE
InternalError when using mockito 5.3 with -XX:+AllowEnhancedClassRedefinition 

### ISSUE THREAD

**Issue by schmidti159** [JetBrains/JetBrainsRuntime#259] opened 2023-11-28 13:15 UTC
Hi, 
we recently upgraded from Spring Boot 2.7 to Spring Boot 3.1 and with this we also upgraded mockito from 4.5.1 to 5.3.1 and bytebuddy from 1.12.23 to 1.14.10.

We use JBR in our development flow with `-XX:+AllowEnhancedClassRedefinition` to have faster development cycles when working on UI tests so no restart is required.

After the upgrade we see exceptions caused by `java.lang.InternalError` in our tests when we use JBR with this flag.

I uploaded a minimal reproducer here: https://github.com/schmidti159/reproducer_for-internal_error_in_jbr_with_mockito

The readme also contains the complete stacktrace and steps how to reproduce.

I am using IntelliJ IDEA 2023.2.5 to start the test and could reproduce it with JBR version 17.0.9+7-b1087.3

Could you please have a look? Having enhanced class redefinition is very valuable to our development workflow.

**Comment by mkartashev** [comment] 2023-11-28 13:33
Thanks for reporting this, I filed [JBR-6363](https://youtrack.jetbrains.com/issue/JBR-6363) in our issue tracker.

**Comment by skybber** [comment] 2023-12-12 14:25
This problem is a bit more difficult. The sample program uses PowerMock, which redefines `java.lang.Object`, which results in redefining all subclasses, i.e. almost all the classes just loaded in `ClassLoader`. In this case, there are ~4,000 classes. The size wouldn't be such a problem, but the problem is that it redefines `java.lang.Object`, which has a lot of bindings and dependencies in the JVM and the current DCEVM doesn't support redefinition of this class. However, a fix is being worked on, but it won't be in the short term, this is a major intervention in the DCEVM code.

**Comment by schmidti159** [comment] 2024-01-11 16:04
Thank you for your analysis. I was not aware that the sample was using PowerMock explicitly, so I looked at it again. 
The root cause of why it only occurred now, is that Mockito changed the default MockMaker with version 5. Before it was using the subclass MockMaker, now the default is the inline MockMaker (see https://github.com/mockito/mockito/releases/tag/v5.0.0).

So if the subclass MockMaker is enough for the current project a simple workaround is to add this dependency to the project:
```xml
    <dependency>
      <groupId>org.mockito</groupId>
      <artifactId>mockito-subclass</artifactId>
      <scope>test</scope>
    </dependency>
```

**Comment by skybber** [comment] 2024-01-22 09:25
There is a jbr branch with the patch available at:

https://github.com/JetBrains/JetBrainsRuntime/tree/vladimir.dvorak/JBR-6363

if you know how to build a JDK, it would be great if you could try it on your case, but don't feel it's necessary

**Comment by skybber** [comment] 2024-02-12 06:53
New release https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.10b1186.1 support redefinition of `java.lang.object`, so this issue should be fixed now

**Closed** 2024-02-13 07:56 UTC

**Comment by tfactor2** [comment] 2025-05-08 17:32
We faced a very similar issue on JBR 21 and Spring Boot 3.3.4 (Mockito 5.14.2).
Actually, JBR (including the latest 21.0.6) doesn't work with any kind of Spring mock (including the new one `@MockitoSpyBean`).

```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method 'void java.util.concurrent.ThreadPoolExecutor.<init>(int, int, long, java.util.concurrent.TimeUnit, java.util.concurrent.BlockingQueue, java.util.concurrent.ThreadFactory, java.util.concurrent.RejectedExecutionHandler)' the class loader 'app' of the current class, org/springframework/scheduling/concurrent/ThreadPoolTaskExecutor$1, and the class loader 'bootstrap' for the method's defining class, java/util/concurrent/ThreadPoolExecutor, have different Class objects for the type java/util/concurrent/RejectedExecutionHandler used in the signature (org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1 is in unnamed module of loader 'app'; java.util.concurrent.ThreadPoolExecutor is in module java.base of loader 'bootstrap')
	at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor$1.<init>(ThreadPoolTaskExecutor.java:285)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   JbrEnhancedClassRedefinitionTest » IllegalArgument Class [org.springframework.test.context.transaction.TransactionalTestExecutionListener] is not assignable to factory type [org.springframework.test.context.TestExecutionListener]       
```

In other cases (not reflected in the reproducer) we got:
```java
Caused by: java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/apache/catalina/loader/WebappLoader.setPermissions()V @62: invokevirtual
  Reason:
    Type 'java/io/FilePermission' (current frame, stack[1]) is not assignable to 'java/security/Permission'
  Current Frame:
    bci: @62
    flags: { }
    locals: { 'org/apache/catalina/loader/WebappLoader', 'jakarta/servlet/ServletContext', 'java/io/File', 'java/lang/String' }
    stack: { 'org/apache/catalina/loader/WebappClassLoaderBase', 'java/io/FilePermission' }
  Bytecode:
```

We believe all these issues have the same cause.

After adding in `pom.xml`:
```xml
<dependency>
  <groupId>org.mockito</groupId>
  <artifactId>mockito-subclass</artifactId>
  <scope>test</scope>
</dependency>
```
the problem was resolved.
Here is the reproducer - https://github.com/tfactor2/reproducer-jbr-enhanced-class-redifinition.

@skybber - I added the comment in an already closed issue; if needed, I can create a separate issue, no problem.

**Comment by skybber** [comment] 2025-06-03 06:59
Sorry for the delayed response, and thank you for bringing this up. We’ll take a closer look at the issue and investigate further.
